### ISSUE TITLE
ServiceMonitors should be dealt with by top level operator

### ISSUE THREAD

**Issue by leifmadsen** [redhat-service-assurance/smart-gateway-operator#9]
Currently the Smart Gateway Operator will create the `ServiceMonitor` when it instantiates a metrics SG. Creation of a `ServiceMonitor` is probably invalid for this Operator since that should probably be dealt with externally (or via a wrapper / top level Operator).

Will require coordination with the `telemetry-framework` repo etc.

**Comment by leifmadsen** [comment]
At this point there isn't really anything to do since we don't have a top level operator right now (that'll come with the migration to Operator Lifecycle Manager). Just wanted to note that we should remove this when we get far enough down the line that we have that Service Assurance Operator.

**Comment by csibbitt** [comment]
This is done. It's in the Service Assurance Operator now: https://github.com/redhat-service-assurance/service-assurance-operator/blob/master/roles/serviceassurance/tasks/component_servicemonitor.yml

And this PR removes it from the SGO: https://github.com/redhat-service-assurance/smart-gateway-operator/pull/27/files#diff-e46d2eb07eed6f2d5429e475cafe6e63L24
